// examples/vue-ts/src/components/Switch/Switch.vue
<script setup lang="ts">
defineProps<{
  defaultChecked?: boolean;
}>();

defineEmits<{
  change: [];
}>();
</script>

<template>
  <label class="switch">
    <input class="switch_input" type="checkbox" :checked="defaultChecked" @change="$emit('change')" />
    <span class="switch_slider" />
  </label>
</template>

<style src="./Switch.styles.scss" lang="scss"></style>

// examples/react-ts/src/components/Switch/Switch.tsx
import type React from 'react';
import './Switch.styles.scss';

type TSwitchProperties = {
  defaultChecked?: boolean
  onChange?: () => void
};

export const Switch: React.FC<TSwitchProperties> = ({ onChange, defaultChecked }) => (
  <label className="switch">
    <input className='switch_input' type="checkbox" checked={defaultChecked} onChange={onChange} />
    <span className="switch_slider" />
  </label>
);
