// examples/vue-ts/src/components/NoiseCanvas/NoiseCanvas.vue
<script setup lang="ts">
import { useTemplateRef } from 'vue';

import { AbstractionAnimation, Config } from '../../abstraction';
import { ThemeMode, useAppTheme } from '../../composables/useAppTheme';
import { useCanvas } from '../../composables/useCanvas';

const abstraction = new AbstractionAnimation();
const { mode } = useAppTheme();

const canvasReference = useTemplateRef<HTMLCanvasElement>('canvas');

useCanvas(canvasReference, abstraction.draw.bind(abstraction), {
  backgroundColor: () => (mode.value === ThemeMode.DARK ? Config.backgroundColorDark : Config.backgroundColor),
});
</script>

<template>
  <canvas ref="canvas" class="noise-abstraction" />
</template>

<style src="./NoiseCanvas.styles.scss" lang="scss"></style>

// examples/react-ts/src/components/NoiseCanvas/NoiseCanvas.tsx
import { useCanvas } from '../../hooks/useCanvas';
import { Config, AbstractionAnimation } from './abstraction';
import type React from 'react';
import { useAppTheme } from '../../hooks/useAppTheme';
import "./NoiseCanvas.styles.scss";

const abstraction = new AbstractionAnimation();

export const NoiseCanvas: React.FC = () => {
  const { mode } = useAppTheme();
  const canvasReference = useCanvas(abstraction.draw.bind(abstraction), {
    backgroundColor: mode === 'dark' ? Config.backgroundColorDark : Config.backgroundColor
  });

  return (
    <canvas ref={canvasReference} className="noise-abstraction" />
  );
};
